# all_bars.pml — loads best concordance/native_ala/free_design for all 12 bars
# Generated by analysis/11_pymol_export.py
bg_color black
set ray_shadows, 0
set antialias, 2

# --- bar_0 (concordance unusual (22 hits); free_design pulls into common fold (1170 hits)) ---
# FoldSeek: conc=22 na=273 free=1170
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_0/concordance_model_0.pdb, bar_0_concordance
color cyan, bar_0_concordance
show cartoon, bar_0_concordance
hide lines, bar_0_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_0/native_ala_model_0.pdb, bar_0_native_ala
color tv_orange, bar_0_native_ala
show cartoon, bar_0_native_ala
hide lines, bar_0_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_0/free_design_model_0.pdb, bar_0_free_design
color purple, bar_0_free_design
show cartoon, bar_0_free_design
hide lines, bar_0_free_design
align bar_0_native_ala, bar_0_concordance
align bar_0_free_design, bar_0_concordance

# --- bar_3 (native_ala structurally novel (6 hits); lyric AAs encode unusual fold) ---
# FoldSeek: conc=1071 na=6 free=1164
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_3/concordance_model_0.pdb, bar_3_concordance
color cyan, bar_3_concordance
show cartoon, bar_3_concordance
hide lines, bar_3_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_3/native_ala_model_0.pdb, bar_3_native_ala
color tv_orange, bar_3_native_ala
show cartoon, bar_3_native_ala
hide lines, bar_3_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_3/free_design_model_0.pdb, bar_3_free_design
color purple, bar_3_free_design
show cartoon, bar_3_free_design
hide lines, bar_3_free_design
align bar_3_native_ala, bar_3_concordance
align bar_3_free_design, bar_3_concordance

# --- bar_6 (TIM barrel — all three buckets hit known folds; concordance top_prob=0.997) ---
# FoldSeek: conc=2596 na=1565 free=1922
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_6/concordance_model_0.pdb, bar_6_concordance
color cyan, bar_6_concordance
show cartoon, bar_6_concordance
hide lines, bar_6_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_6/native_ala_model_0.pdb, bar_6_native_ala
color tv_orange, bar_6_native_ala
show cartoon, bar_6_native_ala
hide lines, bar_6_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_6/free_design_model_0.pdb, bar_6_free_design
color purple, bar_6_free_design
show cartoon, bar_6_free_design
hide lines, bar_6_free_design
align bar_6_native_ala, bar_6_concordance
align bar_6_free_design, bar_6_concordance

# --- bar_8 (native_ala near-novel (3 hits); concordance and free_design known) ---
# FoldSeek: conc=1237 na=3 free=826
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_8/concordance_model_0.pdb, bar_8_concordance
color cyan, bar_8_concordance
show cartoon, bar_8_concordance
hide lines, bar_8_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_8/native_ala_model_0.pdb, bar_8_native_ala
color tv_orange, bar_8_native_ala
show cartoon, bar_8_native_ala
hide lines, bar_8_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_8/free_design_model_0.pdb, bar_8_free_design
color purple, bar_8_free_design
show cartoon, bar_8_free_design
hide lines, bar_8_free_design
align bar_8_native_ala, bar_8_concordance
align bar_8_free_design, bar_8_concordance

# --- bar_9 (native_ala near-novel (3 hits); free_design → Human Saposin A (prob=0.537)) ---
# FoldSeek: conc=536 na=3 free=287
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_9/concordance_model_0.pdb, bar_9_concordance
color cyan, bar_9_concordance
show cartoon, bar_9_concordance
hide lines, bar_9_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_9/native_ala_model_0.pdb, bar_9_native_ala
color tv_orange, bar_9_native_ala
show cartoon, bar_9_native_ala
hide lines, bar_9_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_9/free_design_model_0.pdb, bar_9_free_design
color purple, bar_9_free_design
show cartoon, bar_9_free_design
hide lines, bar_9_free_design
align bar_9_native_ala, bar_9_concordance
align bar_9_free_design, bar_9_concordance

# --- bar_11 (all three known; no strong structural novelty signal) ---
# FoldSeek: conc=1649 na=1039 free=1330
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_11/concordance_model_0.pdb, bar_11_concordance
color cyan, bar_11_concordance
show cartoon, bar_11_concordance
hide lines, bar_11_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_11/native_ala_model_0.pdb, bar_11_native_ala
color tv_orange, bar_11_native_ala
show cartoon, bar_11_native_ala
hide lines, bar_11_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_11/free_design_model_0.pdb, bar_11_free_design
color purple, bar_11_free_design
show cartoon, bar_11_free_design
hide lines, bar_11_free_design
align bar_11_native_ala, bar_11_concordance
align bar_11_free_design, bar_11_concordance

# --- bar_13 (all three known; all hit same fold family) ---
# FoldSeek: conc=861 na=1144 free=1304
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_13/concordance_model_0.pdb, bar_13_concordance
color cyan, bar_13_concordance
show cartoon, bar_13_concordance
hide lines, bar_13_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_13/native_ala_model_0.pdb, bar_13_native_ala
color tv_orange, bar_13_native_ala
show cartoon, bar_13_native_ala
hide lines, bar_13_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_13/free_design_model_0.pdb, bar_13_free_design
color purple, bar_13_free_design
show cartoon, bar_13_free_design
hide lines, bar_13_free_design
align bar_13_native_ala, bar_13_concordance
align bar_13_free_design, bar_13_concordance

# --- bar_17 (MPNN improved pLDDT AND moved away from known folds (free_design 56 hits); best outcome) ---
# FoldSeek: conc=201 na=1337 free=56
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_17/concordance_model_0.pdb, bar_17_concordance
color cyan, bar_17_concordance
show cartoon, bar_17_concordance
hide lines, bar_17_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_17/native_ala_model_0.pdb, bar_17_native_ala
color tv_orange, bar_17_native_ala
show cartoon, bar_17_native_ala
hide lines, bar_17_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_17/free_design_model_0.pdb, bar_17_free_design
color purple, bar_17_free_design
show cartoon, bar_17_free_design
hide lines, bar_17_free_design
align bar_17_native_ala, bar_17_concordance
align bar_17_free_design, bar_17_concordance

# --- bar_27 (native_ala 0 hits across all DBs — Ganja Burn lyric AAs encode novel fold) ---
# FoldSeek: conc=1344 na=0 free=1440
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_27/concordance_model_0.pdb, bar_27_concordance
color cyan, bar_27_concordance
show cartoon, bar_27_concordance
hide lines, bar_27_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_27/native_ala_model_0.pdb, bar_27_native_ala
color tv_orange, bar_27_native_ala
show cartoon, bar_27_native_ala
hide lines, bar_27_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_27/free_design_model_0.pdb, bar_27_free_design
color purple, bar_27_free_design
show cartoon, bar_27_free_design
hide lines, bar_27_free_design
align bar_27_native_ala, bar_27_concordance
align bar_27_free_design, bar_27_concordance

# --- bar_32 (all three known; consistent pattern) ---
# FoldSeek: conc=1199 na=773 free=1252
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_32/concordance_model_0.pdb, bar_32_concordance
color cyan, bar_32_concordance
show cartoon, bar_32_concordance
hide lines, bar_32_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_32/native_ala_model_0.pdb, bar_32_native_ala
color tv_orange, bar_32_native_ala
show cartoon, bar_32_native_ala
hide lines, bar_32_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_32/free_design_model_0.pdb, bar_32_free_design
color purple, bar_32_free_design
show cartoon, bar_32_free_design
hide lines, bar_32_free_design
align bar_32_native_ala, bar_32_concordance
align bar_32_free_design, bar_32_concordance

# --- bar_46 (backbone failure — free_design 0 hits is failure not novelty; dropout) ---
# FoldSeek: conc=636 na=418 free=0
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_46/concordance_model_0.pdb, bar_46_concordance
color cyan, bar_46_concordance
show cartoon, bar_46_concordance
hide lines, bar_46_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_46/native_ala_model_0.pdb, bar_46_native_ala
color tv_orange, bar_46_native_ala
show cartoon, bar_46_native_ala
hide lines, bar_46_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_46/free_design_model_0.pdb, bar_46_free_design
color purple, bar_46_free_design
show cartoon, bar_46_free_design
hide lines, bar_46_free_design
align bar_46_native_ala, bar_46_concordance
align bar_46_free_design, bar_46_concordance

# --- bar_77 (all three known; consistent pattern) ---
# FoldSeek: conc=1016 na=1199 free=1210
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_77/concordance_model_0.pdb, bar_77_concordance
color cyan, bar_77_concordance
show cartoon, bar_77_concordance
hide lines, bar_77_concordance
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_77/native_ala_model_0.pdb, bar_77_native_ala
color tv_orange, bar_77_native_ala
show cartoon, bar_77_native_ala
hide lines, bar_77_native_ala
load /Users/tamukamartin/software/rap-protein/rap-snacks-v1/outputs/pymol/bar_77/free_design_model_0.pdb, bar_77_free_design
color purple, bar_77_free_design
show cartoon, bar_77_free_design
hide lines, bar_77_free_design
align bar_77_native_ala, bar_77_concordance
align bar_77_free_design, bar_77_concordance


# Colour legend:
#   cyan      = concordance  (raw lyric-derived)
#   tv_orange = native_ala   (Ala at BJOZXU positions)
#   purple    = free_design  (MPNN optimised)

zoom all
orient all
