"""
11_pymol_export.py
------------------
Organise PDBs for PyMOL inspection and write per-bar .pml command files.

For each of the 12 candidate bars:
  - Copies the best PDB (model_0, highest boltz_plddt) for each bucket into
    outputs/pymol/bar_XX/{concordance,native_ala,free_design}_model_0.pdb
  - Writes outputs/pymol/bar_XX/visualize.pml  — loads and colours all three
    structures for that bar with bucket-specific colouring and alignment
  - Also writes a global outputs/pymol/all_bars.pml that loads every bar in
    sequence (useful for a quick survey session)

Colours:
  concordance  → cyan   (#00d4ff)
  native_ala   → orange (#ff9500)
  free_design  → purple (#a855f7)
  scrambled    → grey   (#888888)

Usage:
  python analysis/11_pymol_export.py
"""

import shutil, csv
from pathlib import Path

ROOT       = Path(__file__).parent.parent
PREDS_ROOT = ROOT / 'outputs/boltz_validation/boltz_outputs'
RESULTS    = ROOT / 'outputs/boltz_validation/boltz_validation_results.csv'
PYMOL_OUT  = ROOT / 'outputs/pymol'
PYMOL_OUT.mkdir(parents=True, exist_ok=True)

BARS = ['bar_0','bar_3','bar_6','bar_8','bar_9','bar_11',
        'bar_13','bar_17','bar_27','bar_32','bar_46','bar_77']

BUCKETS = ['concordance', 'native_ala', 'free_design']

# PyMOL colour names closest to project palette
COLOURS = {
    'concordance': 'cyan',
    'native_ala':  'tv_orange',
    'free_design': 'purple',
}

# FoldSeek hit counts (from Phase 2 complete results) — used in comments / labels
FOLDSEEK = {
    'bar_0':  {'concordance': 22,   'native_ala': 273,  'free_design': 1170},
    'bar_3':  {'concordance': 1071, 'native_ala': 6,    'free_design': 1164},
    'bar_6':  {'concordance': 2596, 'native_ala': 1565, 'free_design': 1922},
    'bar_8':  {'concordance': 1237, 'native_ala': 3,    'free_design': 826},
    'bar_9':  {'concordance': 536,  'native_ala': 3,    'free_design': 287},
    'bar_11': {'concordance': 1649, 'native_ala': 1039, 'free_design': 1330},
    'bar_13': {'concordance': 861,  'native_ala': 1144, 'free_design': 1304},
    'bar_17': {'concordance': 201,  'native_ala': 1337, 'free_design': 56},
    'bar_27': {'concordance': 1344, 'native_ala': 0,    'free_design': 1440},
    'bar_32': {'concordance': 1199, 'native_ala': 773,  'free_design': 1252},
    'bar_46': {'concordance': 636,  'native_ala': 418,  'free_design': 0},
    'bar_77': {'concordance': 1016, 'native_ala': 1199, 'free_design': 1210},
}

NOTES = {
    'bar_0':  'concordance unusual (22 hits); free_design pulls into common fold (1170 hits)',
    'bar_3':  'native_ala structurally novel (6 hits); lyric AAs encode unusual fold',
    'bar_6':  'TIM barrel — all three buckets hit known folds; concordance top_prob=0.997',
    'bar_8':  'native_ala near-novel (3 hits); concordance and free_design known',
    'bar_9':  'native_ala near-novel (3 hits); free_design → Human Saposin A (prob=0.537)',
    'bar_11': 'all three known; no strong structural novelty signal',
    'bar_13': 'all three known; all hit same fold family',
    'bar_17': 'MPNN improved pLDDT AND moved away from known folds (free_design 56 hits); best outcome',
    'bar_27': 'native_ala 0 hits across all DBs — Ganja Burn lyric AAs encode novel fold',
    'bar_32': 'all three known; consistent pattern',
    'bar_46': 'backbone failure — free_design 0 hits is failure not novelty; dropout',
    'bar_77': 'all three known; consistent pattern',
}

# ── Load best PDB per bar per bucket ─────────────────────────────────────────

def find_preds_dir(preds_root):
    """Find the predictions/ directory regardless of nesting."""
    hits = list(preds_root.rglob('predictions'))
    if not hits:
        raise RuntimeError(f'No predictions/ dir under {preds_root}')
    return hits[0]

PREDS_DIR = find_preds_dir(PREDS_ROOT)

# Load results CSV to get best design per bar per bucket
rows = []
with open(RESULTS) as f:
    for r in csv.DictReader(f):
        rows.append(r)

def best_pdb(bar_id, bucket):
    """Return path to model_0 PDB for the highest-plddt sequence in this bucket."""
    candidates = [r for r in rows if r['bar_id'] == bar_id and r['bucket'] == bucket]
    if not candidates:
        return None
    candidates.sort(key=lambda r: float(r['boltz_plddt']), reverse=True)
    for r in candidates:
        name = r['name']
        seq_dir = PREDS_DIR / name
        pdb = seq_dir / f'{name}_model_0.pdb'
        if pdb.exists():
            return pdb, float(r['boltz_plddt']), r['sequence']
    return None

# ── Copy PDBs and write .pml files ────────────────────────────────────────────

all_pml_lines = [
    '# all_bars.pml — loads best concordance/native_ala/free_design for all 12 bars',
    '# Generated by analysis/11_pymol_export.py',
    'bg_color black',
    'set ray_shadows, 0',
    'set antialias, 2',
    '',
]

for bar_id in BARS:
    bar_dir = PYMOL_OUT / bar_id
    bar_dir.mkdir(exist_ok=True)

    plddt_vals = {}
    seqs = {}
    local_pdbs = {}  # bucket -> local pdb path (relative to bar_dir)

    for bucket in BUCKETS:
        result = best_pdb(bar_id, bucket)
        if result is None:
            print(f'  [SKIP] {bar_id} {bucket} — no PDB found')
            continue
        src_pdb, plddt, seq = result
        dst_name = f'{bucket}_model_0.pdb'
        dst = bar_dir / dst_name
        shutil.copy2(src_pdb, dst)
        plddt_vals[bucket] = plddt
        seqs[bucket] = seq
        local_pdbs[bucket] = dst_name
        print(f'  {bar_id}/{dst_name}  pLDDT={plddt:.3f}')

    fs = FOLDSEEK.get(bar_id, {})
    note = NOTES.get(bar_id, '')

    # ── Per-bar visualize.pml ────────────────────────────────────────────────
    pml_path = bar_dir / 'visualize.pml'

    lines = [
        f'# {bar_id}/visualize.pml',
        f'# {note}',
        f'# FoldSeek hits — concordance: {fs.get("concordance","?")}  '
        f'native_ala: {fs.get("native_ala","?")}  '
        f'free_design: {fs.get("free_design","?")}',
        '',
        'bg_color black',
        'set ray_shadows, 0',
        'set antialias, 2',
        f'cd {bar_dir.resolve()}',
        '',
    ]

    loaded = []
    for bucket in BUCKETS:
        if bucket not in local_pdbs:
            continue
        obj = f'{bar_id}_{bucket}'
        loaded.append((bucket, obj))
        lines += [
            f'load {local_pdbs[bucket]}, {obj}',
            f'color {COLOURS[bucket]}, {obj}',
            f'show cartoon, {obj}',
            f'hide lines, {obj}',
        ]

    lines += ['']

    # Align native_ala and free_design onto concordance (reference)
    if 'concordance' in local_pdbs:
        ref_obj = f'{bar_id}_concordance'
        for bucket in ['native_ala', 'free_design']:
            if bucket in local_pdbs:
                obj = f'{bar_id}_{bucket}'
                lines += [f'align {obj}, {ref_obj}']

    lines += ['']
    lines += [
        '# Representation options — uncomment to switch',
        '# show surface, all    # surface view (slow)',
        '# show sticks, all     # all-atom view',
        '# set transparency, 0.5, all',
        '',
        '# pLDDT colouring by b-factor (Boltz stores pLDDT per-residue in B column)',
        '# spectrum b, blue_white_red, all, minimum=0, maximum=1',
        '',
        '# Show as rainbow from N→C terminus',
        '# spectrum count, rainbow, all',
        '',
        'zoom all',
        'orient all',
        '',
    ]

    # Annotation: what to look for
    lines += [
        f'# === What to look for in {bar_id} ===',
        f'# {note}',
    ]

    if bar_id == 'bar_6':
        lines += [
            '# bar_6 concordance is a TIM barrel-like fold (2596 hits, top_prob=0.997)',
            '# bar_6 free_design converges to PII signalling protein (prob=1.000)',
            '# All three buckets are structurally similar — lyric encoded a real fold',
            '# Try: align bar_6_free_design, bar_6_concordance  → should show low RMSD',
        ]
    elif bar_id == 'bar_9':
        lines += [
            '# bar_9 is the top performer (free_design mean pLDDT 0.839)',
            '# native_ala has only 3 FoldSeek hits — structurally unusual',
            '# free_design converges to Human Saposin A fold (helix bundle, prob=0.537)',
            '# Try: show surface, bar_9_free_design  → should see compact helix bundle',
            '# Try: spectrum b, blue_white_red, bar_9_concordance  → see pLDDT gradient',
        ]
    elif bar_id == 'bar_17':
        lines += [
            '# bar_17 HEADLINE: free_design improved pLDDT AND moved away from known folds',
            '# native_ala 1337 hits vs free_design only 56 hits',
            '# Alignment between concordance and free_design will show large RMSD',
            '# This is the best outcome: foldable + structurally novel',
            '# Try: align bar_17_free_design, bar_17_concordance  → large RMSD expected',
        ]
    elif bar_id == 'bar_27':
        lines += [
            '# bar_27 HEADLINE: native_ala has 0 FoldSeek hits across ALL databases',
            '# Ganja Burn lyric amino acids (BJOZXU→Ala) encode a structurally novel fold',
            '# concordance 1344 hits, free_design 1440 hits — but the lyric text itself is novel',
            '# Compare native_ala shape to concordance — distinct topology expected',
            '# Try: show surface, bar_27_native_ala  → inspect the novel fold',
        ]
    elif bar_id == 'bar_46':
        lines += [
            '# bar_46 is a BACKBONE FAILURE — all three structures are disordered',
            '# free_design pLDDT 0.309 even unconstrained — no sequence can fold this backbone',
            '# Included for comparison — this is what failure looks like',
            '# Try: spectrum b, blue_white_red, all  → expect mostly red (low pLDDT)',
        ]
    elif bar_id in ('bar_3', 'bar_8'):
        lines += [
            f'# {bar_id} native_ala near-novel ({fs.get("native_ala","?")} hits)',
            '# Ala substitution at BJOZXU positions creates an unusual fold',
            '# Inspect native_ala shape vs concordance and free_design',
        ]

    lines += ['', 'set_view [\\', '   1,0,0,\\', '   0,1,0,\\', '   0,0,1,\\', '   0,0,-100,\\', '   0,0,0,1 ]']

    pml_path.write_text('\n'.join(lines) + '\n')

    # ── Contribute to all_bars.pml ───────────────────────────────────────────
    all_pml_lines += [
        f'# --- {bar_id} ({note}) ---',
        f'# FoldSeek: conc={fs.get("concordance","?")} na={fs.get("native_ala","?")} free={fs.get("free_design","?")}',
    ]
    for bucket in BUCKETS:
        if bucket not in local_pdbs:
            continue
        obj = f'{bar_id}_{bucket}'
        all_pml_lines += [
            f'load {(bar_dir / local_pdbs[bucket]).resolve()}, {obj}',
            f'color {COLOURS[bucket]}, {obj}',
            f'show cartoon, {obj}',
            f'hide lines, {obj}',
        ]
    # Align to concordance in the master view
    if 'concordance' in local_pdbs:
        ref_obj = f'{bar_id}_concordance'
        for bucket in ['native_ala', 'free_design']:
            if bucket in local_pdbs:
                all_pml_lines += [f'align {bar_id}_{bucket}, {ref_obj}']
    all_pml_lines += ['']

all_pml_lines += [
    '',
    '# Colour legend:',
    '#   cyan      = concordance  (raw lyric-derived)',
    '#   tv_orange = native_ala   (Ala at BJOZXU positions)',
    '#   purple    = free_design  (MPNN optimised)',
    '',
    'zoom all',
    'orient all',
]

(PYMOL_OUT / 'all_bars.pml').write_text('\n'.join(all_pml_lines) + '\n')

print(f'\nDone.')
print(f'  Per-bar PMLs : outputs/pymol/bar_XX/visualize.pml')
print(f'  Master PML   : outputs/pymol/all_bars.pml')
print(f'\nOpen in PyMOL:')
print(f'  pymol outputs/pymol/bar_9/visualize.pml')
print(f'  pymol outputs/pymol/all_bars.pml')
